dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
services:
  - docker
before_install:
  - docker run --name arangodb -p 8529:8529 -d -e ARANGO_NO_AUTH=1 arangodb/arangodb
install:
  - pip install poetry
  - poetry install
script:
  - poetry run pylint -E migrado
  - poetry run pytest -svv --cov=migrado
